import Foundation

enum LocalizationData_zhHans {
    static let table: [String: String] = [
        // MARK: - Language settings
        "lang.system": "跟随系统",
        "lang.simplified_chinese": "简体中文",
        "lang.traditional_chinese": "繁體中文",
        "lang.english": "English",
        "settings.language": "语言",
        "settings.language.section": "语言",
        "settings.language.picker": "界面语言",

        // MARK: - App / Root
        "app.title": "Tokenomics",
        "toolbar.refresh": "刷新",
        "toolbar.refresh.help": "立即拉取所有 Collector",
        "sidebar.section.overview": "总览",
        "sidebar.section.providers": "供应商",
        "sidebar.breakeven": "回本没",
        "sidebar.dashboard": "仪表盘",
        "sidebar.models": "模型分布",
        "sidebar.tasks": "任务详情",
        "sidebar.logs": "拉取日志",
        "logs.title": "拉取日志",
        "logs.clear": "清空",
        "common.provider_not_exist": "供应商不存在",

        // MARK: - Tasks (Claude Code session-level usage)
        "tasks.title": "任务详情",
        "tasks.reload": "重新扫描 ~/.claude/projects 与 ~/.codex/sessions",
        "tasks.filter.provider": "模型提供商",
        "tasks.filter.all_providers": "全部提供商",
        "tasks.filter.project": "项目",
        "tasks.filter.all_projects": "全部项目",
        "tasks.sort": "排序",
        "tasks.sort.cost": "按花费",
        "tasks.sort.tokens": "按 Token",
        "tasks.sort.recent": "按最近",
        "tasks.subtitle.fmt": "共 %d / %d 个任务",
        "tasks.empty.title": "未发现任务",
        "tasks.empty.desc": "请确认 Claude Code 或 Codex 已在本机使用过，并已生成 ~/.claude/projects 或 ~/.codex/sessions 下的会话日志。",
        "tasks.detail.empty.title": "选择左侧任务查看详情",
        "tasks.detail.empty.desc": "每个任务对应一个 Claude Code 或 Codex 会话（一个 .jsonl 文件）。",
        "tasks.stat.cost": "总花费",
        "tasks.stat.tokens": "总 Token",
        "tasks.stat.messages": "请求次数",
        "tasks.stat.duration": "持续时长",
        "tasks.by_model": "按模型拆分",
        "tasks.col.model": "模型",
        "tasks.col.input": "输入",
        "tasks.col.output": "输出",
        "tasks.col.cache_w": "缓存写",
        "tasks.col.cache_r": "缓存读",
        "tasks.col.cost": "费用",
        "tasks.by_turn": "按用户轮次拆分",
        "tasks.by_turn.hint": "每一行 = 一次你输入的指令以及它引发的全部模型回复（含 sidechain）",
        "tasks.by_turn.empty": "未识别到用户输入轮次。",
        "tasks.turn.tokens.fmt": "Token %@",
        "tasks.turn.replies.fmt": "回复 %d 次",
        "tasks.meta": "会话元信息",
        "tasks.meta.cwd": "工作目录",
        "tasks.meta.branch": "Git 分支",
        "tasks.meta.file": "日志文件",
        "tasks.meta.first": "起始时间",
        "tasks.meta.last": "结束时间",

        // MARK: - Tasks: quota share & chart
        "tasks.quota_share.title": "占订阅额度比例",
        "tasks.quota_share.hint": "按当前 utilization 在同 5 小时 / 每周窗口内的所有任务间按 token 量分摊估算。",
        "tasks.quota_share.five_hour": "5 小时限额",
        "tasks.quota_share.weekly": "每周限额",
        "tasks.quota_share.of_limit": "限额",
        "tasks.quota_share.window_used.fmt": "窗口当前用量 %@",
        "tasks.quota_share.no_snapshot": "暂无额度快照，请到仪表盘刷新。",
        "tasks.project_timeline.title": "项目用量时间轴",
        "tasks.project_timeline.hint": "每个点代表该项目的一次任务，右侧菜单可切换纵轴含义。",
        "tasks.project_timeline.x": "时间",
        "tasks.project_timeline.empty": "该项目暂无任务记录。",
        "tasks.project_timeline.count.fmt": "已绘制 %d 个任务",
        "tasks.project_timeline.metric.input": "输入 Token",
        "tasks.project_timeline.metric.output": "输出 Token",
        "tasks.project_timeline.metric.cache_read": "缓存命中 Token",
        "tasks.project_timeline.metric.cache_creation": "缓存创建 Token",
        "tasks.project_timeline.metric.cost": "费用",
        "tasks.project_timeline.range.day1": "过去 1 天",
        "tasks.project_timeline.range.day3": "过去 3 天",
        "tasks.project_timeline.range.day7": "过去 7 天",
        "tasks.project_timeline.range.day30": "过去 30 天",
        "tasks.project_timeline.range.all": "全部",

        // MARK: - Settings tabs
        "settings.tab.keys": "API Keys",
        "settings.tab.providers": "供应商",
        "settings.tab.subscriptions": "订阅",
        "settings.tab.quotaSources": "额度采集",
        "settings.tab.display": "显示",
        "settings.tab.pricing": "单价",
        "settings.tab.data": "数据",

        // MARK: - Settings: API Keys
        "settings.keys.intro": "在下方为各个服务商填写 API Key，App 会用它们去拉取用量或余额。",
        "settings.keys.col.provider": "服务商",
        "settings.keys.col.provider.sub": "AI 服务名称",
        "settings.keys.col.usage": "用途",
        "settings.keys.col.usage.sub": "该 Key 用于调用哪个接口",
        "settings.keys.col.apikey": "API Key",
        "settings.keys.col.apikey.sub": "粘贴你的密钥并点击「保存」",
        "settings.keys.security": "密钥保存在系统 Keychain 中，不会随数据库导出。",
        "settings.keys.section.note": "说明",
        "settings.keys.section.list": "密钥列表",
        "settings.keys.empty": "所有内置供应商均已在「供应商」标签下隐藏。",
        "settings.keys.placeholder.set": "已设置（输入新值覆盖）",
        "settings.keys.placeholder.unset": "未设置",
        "common.save": "保存",
        "common.delete": "删除",
        "common.cancel": "取消",
        "common.add": "添加",
        "common.edit": "编辑",
        "common.confirm": "确定",

        // MARK: - Settings: Display
        "settings.display.appearance": "外观",
        "settings.display.mode": "显示模式",
        "settings.display.currency": "货币",
        "settings.display.currency.label": "显示",
        "settings.display.rate": "当前汇率",
        "settings.display.rate.refresh": "刷新",

        // MARK: - Appearance modes
        "appearance.system": "跟随系统",
        "appearance.light": "白色模式",
        "appearance.dark": "暗黑模式",

        // MARK: - Currency
        "currency.usd": "美元 (USD)",
        "currency.cny": "人民币 (CNY)",
        "currency.both": "双显示",

        // MARK: - Provider display names
        "provider.anthropic":   "Anthropic",
        "provider.openai":      "OpenAI",
        "provider.unknown":     "未知",

        // MARK: - Pricing
        "pricing.title": "模型单价（USD per 1M tokens）",
        "pricing.desc": "已内置 Anthropic / OpenAI 等常用模型公开单价；如需覆盖，填写下方表单或在列表中点击「覆盖」。",
        "pricing.search": "搜索 provider 或 model",
        "pricing.col.model": "模型",
        "pricing.col.input": "输入",
        "pricing.col.output": "输出",
        "pricing.col.cacheWrite": "缓存写",
        "pricing.col.cacheRead": "缓存读",
        "pricing.custom_entries": "自定义条目",
        "pricing.overridden": "已覆盖",
        "pricing.add_section": "手动添加 / 覆盖单价",
        "pricing.placeholder.key": "key (provider:model)",
        "pricing.placeholder.input": "input",
        "pricing.placeholder.output": "output",
        "pricing.help.fill_form": "把当前价格填入下方表单以便覆盖",
        "pricing.help.remove_override": "移除覆盖，恢复内置单价",

        // MARK: - Data
        "data.section.db": "数据库",
        "data.records.total": "记录总数",
        "data.section.actions": "操作",
        "data.fetch_now": "立即拉取一次",
        "data.export_csv": "导出 CSV",
        "data.section.path": "路径",
        "data.path.desc": "数据存储于 macOS SwiftData 容器（沙盒内 ~/Library/Containers/com.tokenomics.Tokenomics）",

        // MARK: - Providers settings
        "providers.intro": "控制 App 中显示哪些供应商图标。隐藏后将从侧边栏、仪表盘汇总、API Keys 列表中移除。",
        "providers.tab.builtin": "内置",
        "providers.tab.custom": "自定义",
        "providers.toggle.show": "显示",
        "providers.toggle.collect": "拉取",
        "providers.toggle.collect.help": "启用后会按 5 分钟间隔自动拉取",
        "providers.custom.title": "自定义供应商",
        "providers.custom.empty": "还没有自定义供应商。点击「新增」可以添加一个外部脚本端点。",
        "providers.custom.no_endpoint": "未配置端点",
        "common.new": "新增",
        "custom.editor.new": "新增自定义供应商",
        "custom.editor.edit": "编辑自定义供应商",
        "custom.editor.section.basic": "基础",
        "custom.editor.section.http": "HTTP",
        "custom.editor.section.mapping": "字段映射",
        "custom.editor.name": "名称（显示用）",
        "custom.editor.color": "颜色",
        "custom.editor.enable_collect": "启用自动拉取",
        "custom.editor.endpoint": "Endpoint URL",
        "custom.editor.method": "方法",
        "custom.editor.headers": "Headers (JSON)",
        "custom.editor.body": "Body (JSON)",
        "custom.editor.records_path": "记录数组路径 (recordsPath，留空表示根本身是数组)",
        "custom.editor.model_field": "模型字段",
        "custom.editor.input_field": "input tokens 字段",
        "custom.editor.output_field": "output tokens 字段",
        "custom.editor.timestamp_field": "时间戳字段（可选）",
        "custom.editor.cost_field": "费用 USD 字段（可选）",
        "custom.editor.requestid_field": "请求 ID 字段（可选，用于去重）",
        "custom.editor.mapping.footer": "路径语法：a.b[0].c  例：data.records 表示根对象 data 下的 records 数组",
        "custom.editor.unnamed": "未命名",

        // MARK: - Subscriptions
        "subs.title": "订阅套餐",
        "subs.desc": "添加你已订阅的 ChatGPT Plus / Claude Pro 等，用来在「回本没」页面计算回本率。",
        "subs.empty.title": "还没有订阅记录",
        "subs.empty.desc": "点击右上角「新增」从预设套餐里挑选，或自定义月费。",
        "subs.monthly.fmt": "$%.2f / 月",
        "subs.editor.new": "新增订阅",
        "subs.editor.edit": "编辑订阅",
        "subs.editor.preset_section": "快速选择预设",
        "subs.editor.preset_picker": "预设套餐",
        "subs.editor.preset_custom": "（自定义）",
        "subs.editor.basic": "基础信息",
        "subs.editor.provider": "供应商",
        "subs.editor.plan_name": "套餐名（如 Plus / Pro / Max 20x）",
        "subs.editor.monthly_usd": "月费 (USD)",

        // MARK: - Quota Sources
        "quota.title": "Claude 订阅额度采集",
        "quota.desc": "Claude 的 5 小时 / 每周 额度可以从两条数据源拉取。OAuth 接口虽然官方，但被限流（HTTP 429）的几率高；浏览器 Cookie 路径走 claude.ai 网页 API，限流策略独立，是 OAuth 被限流时的兜底。",
        "quota.primary": "主路径",
        "quota.primary.oauth": "OAuth 接口（默认）",
        "quota.primary.cookie": "浏览器 Cookie（绕开 OAuth 限流）",
        "quota.primary.cookie_desc": "首选从本地浏览器读 claude.ai cookie，失败时回退到 OAuth。",
        "quota.primary.oauth_desc": "首选 OAuth；遇到 429 / 401 时自动回退到浏览器 Cookie。",
        "quota.browser.priority": "浏览器优先级",
        "quota.browser.priority.desc": "从上到下尝试，先成功的浏览器优先使用其 cookie。点开关切换是否启用某个浏览器。",
        "quota.test": "连通性测试",
        "quota.test.run": "立即从浏览器读取 cookie",
        "quota.test.running": "正在测试…",
        "quota.test.keychain_hint": "第一次读取会弹出系统钥匙串授权，点「始终允许」即可。",

        // MARK: - Dashboard
        "dashboard.title": "AI Token 用量仪表盘",
        "dashboard.rate.fmt": "汇率 1 USD = ¥%@",
        "dashboard.rate.last_update.fmt": " · 上次更新 %@",
        "dashboard.picker.currency": "货币",
        "dashboard.section.quota": "订阅额度（Claude / Codex）",
        "dashboard.section.trend": "过去 14 天趋势",
        "dashboard.section.by_provider": "按供应商汇总（本月）",
        "dashboard.section.recent": "最近 30 条明细",
        "dashboard.empty.title": "暂无数据",
        "dashboard.empty.desc": "请在「设置」中配置 API Key，或确保 Claude Code 已在本机产生过日志。",
        "dashboard.cost.today": "今日",
        "dashboard.cost.week": "本周",
        "dashboard.cost.month": "本月",
        "dashboard.cost.total": "累计",
        "dashboard.recordrow.io.fmt": "in %@ · out %@",

        // MARK: - Dashboard: 5-hour limit breakdown (top section)
        "dashboard.five_hour.section": "5 小时限额",
        "dashboard.five_hour.pick_hint": "选择一个供应商，查看当前 5 小时滚动窗口的使用情况，以及今日每个任务占了多少百分比。",
        "dashboard.five_hour.window_used.fmt": "窗口当前使用率 %@",
        "dashboard.five_hour.window_resets.fmt": "%@ 重置",
        "dashboard.five_hour.no_snapshot": "尚未获取到该供应商的额度快照，请尝试刷新。",
        "dashboard.five_hour.empty_tasks": "当前 5 小时窗口内没有任务记录。",
        "dashboard.five_hour.by_task": "今日窗口内的任务",
        "dashboard.five_hour.col.task": "任务",
        "dashboard.five_hour.col.project": "项目",
        "dashboard.five_hour.col.time": "最近活动",
        "dashboard.five_hour.col.tokens": "Token",
        "dashboard.five_hour.col.share": "占 5h 限额",
        "dashboard.five_hour.total.fmt": "今日窗口内：%d 个任务 · %@ tokens · 共占 %@",

        // MARK: - Provider detail
        "provider_detail.count_total.fmt": "共 %d 条 · 累计 %@",
        "provider_detail.empty.title.fmt": "暂无 %@ 数据",
        "provider_detail.empty.desc": "配置 API Key 后等待下次定时拉取，或确认对应本地日志路径存在。",
        "provider_detail.by_model": "按模型",
        "provider_detail.recent": "最近明细",
        "provider_detail.api_key_guide.fmt": "如何获取 %@",
        "provider_detail.tokens.fmt": "%@ tokens",

        // MARK: - Model breakdown
        "models.title": "模型分布",
        "models.empty": "暂无数据",
        "models.col.model": "模型",
        "models.col.provider": "供应商",
        "models.col.tokens": "Token",
        "models.col.cost": "花费",
        "models.chart.cost": "花费",
        "models.chart.date": "日期",
        "models.chart.provider": "供应商",
        "models.chart.cost_usd": "花费 USD",

        // MARK: - Quota card
        "quotacard.empty": "无可显示的额度窗口",
        "quotacard.updated.fmt": "更新于 %@ · %@",
        "quotacard.reset.fmt": "将于 %@ 重置",
        "quotacard.usage.title": "用量",
        "quotacard.usage.today": "今日",
        "quotacard.usage.week": "近 7 天",
        "quotacard.usage.month": "近 30 天",
        "quotacard.usage.tokens.fmt": "%@ tokens",

        // MARK: - Provider row / Cost card / Usage chart
        "providerrow.subtitle.fmt": "%d 条 · %@ tokens",
        "costcard.tokens.fmt": "%@ tokens",
        "usagechart.x.date": "日期",
        "usagechart.y.cost_usd": "花费 USD",
        "usagechart.legend.provider": "供应商",

        // MARK: - Breakeven
        "breakeven.header.fmt": "%@ · %@",
        "breakeven.tier.title": "套餐生效",
        "breakeven.tier.subtitle": "开始使用",
        "breakeven.first_breakeven": "首次回本",
        "breakeven.rate_300": "回本率 300%",
        "breakeven.timeline.milestone.fmt": "回本率达到 %d%% · 价值 %@",
        "breakeven.timeline.current.fmt": "回本率 %.0f%% (当前)",
        "breakeven.timeline.value.fmt": "价值达到 %@",
        "breakeven.hero.cheers": "恭喜你！",
        "breakeven.hero.keep_going": "继续加油！",
        "breakeven.hero.title.done": "已回本！",
        "breakeven.hero.title.almost": "还差一点",
        "breakeven.hero.subtitle.fmt": "你已经赚回套餐费用的 %@ 倍 🎉",
        "breakeven.metric.paid": "支付金额",
        "breakeven.metric.paid.sub": "本月套餐支出",
        "breakeven.metric.value": "获得价值",
        "breakeven.metric.value.sub": "Token 等值价值",
        "breakeven.metric.saved": "节省金额",
        "breakeven.metric.saved.sub": "相当于省下",
        "breakeven.tier.fire": "血赚级用户",
        "breakeven.tier.diamond": "回本达人",
        "breakeven.tier.done": "已回本",
        "breakeven.tier.almost": "接近回本",
        "breakeven.tier.newbie": "新手用户",
        "breakeven.badge.usage_reached": "你的 Token 使用量已经达到",
        "breakeven.badge.plan_value.fmt": "%@ 套餐价值的",
        "breakeven.badge.multiples.fmt": "%.2f 倍",
        "breakeven.badge.surpassed": "超过了",
        "breakeven.badge.users": "的用户",
        "breakeven.invret.title": "投入 vs 回报",
        "breakeven.invret.desc": "用更少的钱，获得了更多的价值",
        "breakeven.invret.rate": "回本率",
        "breakeven.invret.paid": "支付",
        "breakeven.invret.gained": "获得价值",
        "breakeven.timeline.title": "回本时间线",
        "breakeven.timeline.date_fmt": "M月d日",
        "breakeven.overview.title.fmt": "使用概览 (%@)",
        "breakeven.overview.tokens": "Token 使用量",
        "breakeven.overview.requests": "请求次数",
        "breakeven.overview.month_eq": "本月等值",
        "breakeven.overview.view_models": "查看模型分布",
        "breakeven.api.title": "如果按 API 计费",
        "breakeven.api.desc.fmt": "如果你直接通过 %@ API 使用\n本月你需要支付",
        "breakeven.api.saved": "相当于省下",
        "breakeven.api.saved_pct.fmt": "省了 %.1f%%",
        "breakeven.api.now_paid": "而现在你只支付了",
        "breakeven.api.plan_cost.fmt": "%@ 套餐费用",
        "breakeven.tip.label": "💡 小贴士",
        "breakeven.tip.done.fmt": "继续保持！你正在充分利用 %@ 套餐的强大能力 ✨",
        "breakeven.tip.almost": "再多用一些，距离回本只差一点啦 💪",
        "breakeven.empty.title": "还没添加任何订阅",
        "breakeven.empty.desc": "请到「设置 → 订阅」中添加你订阅的 ChatGPT Plus / Claude Pro 等套餐。\n如果你登录了 Claude Code / Codex CLI，回到「仪表盘」等几秒，订阅会被自动识别。",

        // MARK: - Probe results
        "probe.ok.fmt": "✓ 已从 %@/%@ 读到 sessionKey（…%@），host=%@",
        "probe.err.fmt": "✗ %@",
        "quota.probe.success.fmt": "已从 %@/%@ 读到 sessionKey（…%@），host=%@",

        // MARK: - API Key 标签 & 说明
        "apikey.hint.openai":      "从 api.openai.com 拉取 /v1/organization/costs 费用数据",
        "apikey.hint.anthropic":   "从 api.anthropic.com 拉取 /v1/organizations/usage_report 使用数据",

        // MARK: - ChromiumBrowser errors
        "browser.not_installed.fmt": "%@ 未安装",
        "browser.no_cookies.fmt": "%@ 未找到 Cookies 文件",
        "browser.sqlite_unavailable": "系统未提供 /usr/bin/sqlite3",
        "browser.sqlite_failed.fmt": "读取 SQLite 失败：%@",
        "browser.no_session_key.fmt": "%@ 没有 claude.ai 的 sessionKey（请先登录 claude.ai）",
        "browser.keychain_missing.fmt": "%@ Safe Storage 密钥不存在",
        "browser.keychain_denied.fmt": "%@ Safe Storage 钥匙串访问被拒绝（OSStatus=%@）",
        "browser.decrypt_failed.fmt": "cookie 解密失败：%@",
    ]
}
