import Foundation

enum LocalizationData_en {
    static let table: [String: String] = [
        // MARK: - Language settings
        "lang.system": "Follow System",
        "lang.simplified_chinese": "简体中文",
        "lang.traditional_chinese": "繁體中文",
        "lang.english": "English",
        "settings.language": "Language",
        "settings.language.section": "Language",
        "settings.language.picker": "Interface Language",

        // MARK: - App / Root
        "app.title": "Tokenomics",
        "toolbar.refresh": "Refresh",
        "toolbar.refresh.help": "Pull all collectors immediately",
        "sidebar.section.overview": "Overview",
        "sidebar.section.providers": "Providers",
        "sidebar.breakeven": "Break-even",
        "sidebar.dashboard": "Dashboard",
        "sidebar.models": "Model Breakdown",
        "sidebar.tasks": "Tasks",
        "sidebar.downgrade": "Downgrade Watch",
        "sidebar.logs": "Fetch Logs",
        "logs.title": "Fetch Logs",
        "logs.clear": "Clear",
        "common.provider_not_exist": "Provider not found",

        // MARK: - Tasks (Claude Code + Codex session-level usage)
        "tasks.title": "Tasks",
        "tasks.reload": "Rescan ~/.claude/projects and ~/.codex/sessions",
        "tasks.filter.provider": "Provider",
        "tasks.filter.all_providers": "All providers",
        "tasks.filter.project": "Project",
        "tasks.filter.all_projects": "All projects",
        "tasks.sort": "Sort",
        "tasks.sort.cost": "By cost",
        "tasks.sort.tokens": "By tokens",
        "tasks.sort.recent": "By recent",
        "tasks.subtitle.fmt": "%d of %d tasks",
        "tasks.empty.title": "No tasks found",
        "tasks.empty.desc": "Make sure Claude Code or Codex has been used on this machine and has produced session logs under ~/.claude/projects or ~/.codex/sessions.",
        "tasks.detail.empty.title": "Select a task on the left",
        "tasks.detail.empty.desc": "Each task corresponds to one Claude Code or Codex session (one .jsonl file).",
        "tasks.stat.cost": "Total cost",
        "tasks.stat.tokens": "Total tokens",
        "tasks.stat.messages": "Requests",
        "tasks.stat.duration": "Duration",
        "tasks.by_model": "By model",
        "tasks.col.model": "Model",
        "tasks.col.input": "Input",
        "tasks.col.output": "Output",
        "tasks.col.cache_w": "Cache W",
        "tasks.col.cache_r": "Cache R",
        "tasks.col.cost": "Cost",
        "tasks.by_turn": "By user turn",
        "tasks.by_turn.hint": "Each row = one of your prompts and all model replies it triggered (incl. sidechains)",
        "tasks.by_turn.empty": "No user turns detected.",
        "tasks.turn.tokens.fmt": "Tokens %@",
        "tasks.turn.replies.fmt": "%d replies",
        "tasks.meta": "Session info",
        "tasks.meta.cwd": "Working dir",
        "tasks.meta.branch": "Git branch",
        "tasks.meta.file": "Log file",
        "tasks.meta.first": "First",
        "tasks.meta.last": "Last",

        // MARK: - Tasks: quota share & chart
        "tasks.quota_share.title": "Share of subscription limit",
        "tasks.quota_share.hint": "Estimated by allocating the live utilization across tasks that ran inside the same 5-hour / weekly window.",
        "tasks.quota_share.five_hour": "5-hour limit",
        "tasks.quota_share.weekly": "Weekly limit",
        "tasks.quota_share.of_limit": "of limit",
        "tasks.quota_share.window_used.fmt": "Window currently at %@",
        "tasks.quota_share.no_snapshot": "No live quota snapshot — see Dashboard.",
        "tasks.project_timeline.title": "Project usage over time",
        "tasks.project_timeline.hint": "Every point is one task from this project; pick what to plot on the Y axis with the menu on the right.",
        "tasks.project_timeline.x": "Time",
        "tasks.project_timeline.empty": "No tasks recorded for this project yet.",
        "tasks.project_timeline.count.fmt": "%d tasks plotted",
        "tasks.project_timeline.metric.input": "Input tokens",
        "tasks.project_timeline.metric.output": "Output tokens",
        "tasks.project_timeline.metric.cache_read": "Cache hit tokens",
        "tasks.project_timeline.metric.cache_creation": "Cache write tokens",
        "tasks.project_timeline.metric.cost": "Cost",
        "tasks.project_timeline.range.day1": "Past 1 day",
        "tasks.project_timeline.range.day3": "Past 3 days",
        "tasks.project_timeline.range.day7": "Past 7 days",
        "tasks.project_timeline.range.day30": "Past 30 days",
        "tasks.project_timeline.range.all": "All",
        // MARK: - Settings tabs
        "settings.tab.keys": "API Keys",
        "settings.tab.providers": "Providers",
        "settings.tab.subscriptions": "Subscriptions",
        "settings.tab.quotaSources": "Quota Sources",
        "settings.tab.display": "Display",
        "settings.tab.pricing": "Pricing",
        "settings.tab.data": "Data",

        // MARK: - Settings: API Keys
        "settings.keys.intro": "Enter your API keys for each provider below; the app will use them to fetch usage or balance.",
        "settings.keys.col.provider": "Provider",
        "settings.keys.col.provider.sub": "AI service name",
        "settings.keys.col.usage": "Usage",
        "settings.keys.col.usage.sub": "What this key is used for",
        "settings.keys.col.apikey": "API Key",
        "settings.keys.col.apikey.sub": "Paste your key and click Save",
        "settings.keys.security": "Keys are stored in the system Keychain and are not included in database exports.",
        "settings.keys.section.note": "Note",
        "settings.keys.section.list": "Key List",
        "settings.keys.empty": "All built-in providers are hidden under the Providers tab.",
        "settings.keys.placeholder.set": "Set (enter new value to override)",
        "settings.keys.placeholder.unset": "Not set",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.cancel": "Cancel",
        "common.add": "Add",
        "common.edit": "Edit",
        "common.confirm": "OK",

        // MARK: - Settings: Display
        "settings.display.appearance": "Appearance",
        "settings.display.mode": "Display Mode",
        "settings.display.currency": "Currency",
        "settings.display.currency.label": "Display",
        "settings.display.rate": "Exchange Rate",
        "settings.display.rate.refresh": "Refresh",

        // MARK: - Appearance modes
        "appearance.system": "Follow System",
        "appearance.light": "Light",
        "appearance.dark": "Dark",

        // MARK: - Currency
        "currency.usd": "US Dollar (USD)",
        "currency.cny": "Chinese Yuan (CNY)",
        "currency.both": "Both",

        // MARK: - Provider display names
        "provider.anthropic":   "Anthropic",
        "provider.openai":      "OpenAI",
        "provider.unknown":     "Unknown",

        // MARK: - Pricing
        "pricing.title": "Model Pricing (USD per 1M tokens)",
        "pricing.desc": "Built-in pricing for common Anthropic / OpenAI models is included. To override, fill in the form below or click Override in the list.",
        "pricing.search": "Search provider or model",
        "pricing.col.model": "Model",
        "pricing.col.input": "Input",
        "pricing.col.output": "Output",
        "pricing.col.cacheWrite": "Cache Write",
        "pricing.col.cacheRead": "Cache Read",
        "pricing.custom_entries": "Custom Entries",
        "pricing.overridden": "Overridden",
        "pricing.add_section": "Add / Override Pricing",
        "pricing.placeholder.key": "key (provider:model)",
        "pricing.placeholder.input": "input",
        "pricing.placeholder.output": "output",
        "pricing.help.fill_form": "Fill the form below with current values for overriding",
        "pricing.help.remove_override": "Remove override and restore built-in pricing",

        // MARK: - Data
        "data.section.db": "Database",
        "data.records.total": "Total Records",
        "data.section.actions": "Actions",
        "data.fetch_now": "Fetch Now",
        "data.export_csv": "Export CSV",
        "data.export_json": "Export JSON",
        "data.section.path": "Path",
        "data.path.desc": "Data is stored in the macOS SwiftData container (~/Library/Containers/com.tokenomics.Tokenomics inside the sandbox).",
        "data.section.export.raw": "Export Raw Data",
        "data.export.raw.desc": "Export every row of raw usage records, ready for Numbers / Excel or downstream pipelines.",
        "data.export.json.include_monthly": "Include monthly summary",
        "data.export.json.include_monthly.help": "Embed a pre-aggregated summary of the selected month at the top of the JSON, so reporting scripts can use it directly.",
        "data.section.export.monthly": "Monthly Report / Expense Statement",
        "data.export.monthly.desc": "Build reconciliation artifacts for the selected month: PDF for expense filing / reviewing with your manager, CSV pre-aggregated by model for Excel, and Markdown to drop into the team chat.",
        "data.export.monthly.month": "Month",
        "data.export.monthly.account": "Account / Team",
        "data.export.monthly.account.placeholder": "Optional, printed in the PDF header",
        "data.export.monthly.pdf": "Export Monthly PDF",
        "data.export.monthly.csv": "Export Monthly CSV",
        "data.export.monthly.copy_md": "Copy Monthly Markdown",
        "data.export.saved.fmt": "✓ Saved to %@",
        "data.export.copied.md.fmt": "✓ Copied %@ monthly Markdown to clipboard",

        // MARK: - Providers settings
        "providers.intro": "Control which provider icons appear in the app. Hidden providers are removed from the sidebar, dashboard summary, and API Keys list.",
        "providers.tab.builtin": "Built-in",
        "providers.tab.custom": "Custom",
        "providers.toggle.show": "Show",
        "providers.toggle.collect": "Collect",
        "providers.toggle.collect.help": "When enabled, fetches automatically every 5 minutes",
        "providers.custom.title": "Custom Providers",
        "providers.custom.empty": "No custom providers yet. Click Add to register an external script endpoint.",
        "providers.custom.no_endpoint": "No endpoint configured",
        "common.new": "Add",
        "custom.editor.new": "Add Custom Provider",
        "custom.editor.edit": "Edit Custom Provider",
        "custom.editor.section.basic": "Basic",
        "custom.editor.section.http": "HTTP",
        "custom.editor.section.mapping": "Field Mapping",
        "custom.editor.name": "Name (for display)",
        "custom.editor.color": "Color",
        "custom.editor.enable_collect": "Enable auto-collect",
        "custom.editor.endpoint": "Endpoint URL",
        "custom.editor.method": "Method",
        "custom.editor.headers": "Headers (JSON)",
        "custom.editor.body": "Body (JSON)",
        "custom.editor.records_path": "Records array path (recordsPath; leave empty if root is the array)",
        "custom.editor.model_field": "Model field",
        "custom.editor.input_field": "input tokens field",
        "custom.editor.output_field": "output tokens field",
        "custom.editor.timestamp_field": "Timestamp field (optional)",
        "custom.editor.cost_field": "Cost USD field (optional)",
        "custom.editor.requestid_field": "Request ID field (optional, for dedup)",
        "custom.editor.mapping.footer": "Path syntax: a.b[0].c  e.g., data.records means the records array inside the data object.",
        "custom.editor.unnamed": "Unnamed",

        // MARK: - Subscriptions
        "subs.title": "Subscriptions",
        "subs.desc": "Add your subscriptions like ChatGPT Plus / Claude Pro to calculate break-even on the Break-even page.",
        "subs.empty.title": "No subscriptions yet",
        "subs.empty.desc": "Click Add at the top right to pick from presets, or customize your own monthly fee.",
        "subs.monthly.fmt": "$%.2f / mo",
        "subs.editor.new": "Add Subscription",
        "subs.editor.edit": "Edit Subscription",
        "subs.editor.preset_section": "Quick Pick Preset",
        "subs.editor.preset_picker": "Preset Plans",
        "subs.editor.preset_custom": "(Custom)",
        "subs.editor.basic": "Basics",
        "subs.editor.provider": "Provider",
        "subs.editor.plan_name": "Plan name (e.g., Plus / Pro / Max 20x)",
        "subs.editor.monthly_usd": "Monthly fee (USD)",

        // MARK: - Quota Sources
        "quota.title": "Claude Subscription Quota",
        "quota.desc": "Claude's 5-hour / weekly quota can be fetched from two data sources. The OAuth endpoint is official but is often rate-limited (HTTP 429); the browser-cookie path uses the claude.ai web API with an independent rate limit and serves as a fallback when OAuth is throttled.",
        "quota.primary": "Primary Path",
        "quota.primary.oauth": "OAuth endpoint (default)",
        "quota.primary.cookie": "Browser cookie (bypass OAuth limit)",
        "quota.primary.cookie_desc": "Prefer reading claude.ai cookies from the local browser; fall back to OAuth on failure.",
        "quota.primary.oauth_desc": "Prefer OAuth; fall back to browser cookies on 429 / 401.",
        "quota.browser.priority": "Browser Priority",
        "quota.browser.priority.desc": "Tried top-to-bottom; the first successful browser's cookies are used. Toggle to enable or disable a browser.",
        "quota.test": "Connectivity Test",
        "quota.test.run": "Read cookies from browser now",
        "quota.test.running": "Testing…",
        "quota.test.keychain_hint": "The first read will prompt for system Keychain access — click \"Always Allow\".",

        // MARK: - Dashboard
        "dashboard.title": "AI Token Usage Dashboard",
        "dashboard.rate.fmt": "Rate 1 USD = ¥%@",
        "dashboard.rate.last_update.fmt": " · Last updated %@",
        "dashboard.picker.currency": "Currency",
        "dashboard.copy_md": "Copy Monthly Summary",
        "dashboard.copy_md.help": "Package the current month's per-provider / per-model summary as Markdown and copy to the clipboard for the team chat.",
        "dashboard.copy_md.copied": "Copied",
        "dashboard.section.quota": "Subscription Quota (Claude / Codex)",
        "dashboard.section.trend": "Past 14 Days",
        "dashboard.section.by_provider": "By Provider (This Month)",
        "dashboard.section.recent": "Latest 30 Records",
        "dashboard.section.cache_hit": "Cache Hit Ratio (cache_read / input + cache_read + cache_write)",
        "dashboard.empty.title": "No data",
        "dashboard.empty.desc": "Configure an API Key in Settings, or make sure Claude Code has produced logs on this machine.",
        "dashboard.cost.today": "Today",
        "dashboard.cost.week": "This Week",
        "dashboard.cost.month": "This Month",
        "dashboard.cost.total": "Total",
        "dashboard.recordrow.io.fmt": "in %@ · out %@",

        // MARK: - Cache hit ratio card
        "cache_hit.breakdown.fmt": "hit %@ · write %@ · input %@",
        "cache_hit.no_data": "—",

        // MARK: - Dashboard: 5-hour limit breakdown (top section)
        "dashboard.five_hour.section": "5-hour Limit",
        "dashboard.five_hour.pick_hint": "Pick a provider to see the 5-hour rolling window and how today's tasks contribute to it.",
        "dashboard.five_hour.window_used.fmt": "Window currently at %@",
        "dashboard.five_hour.window_resets.fmt": "Resets %@",
        "dashboard.five_hour.no_snapshot": "No live quota snapshot for this provider yet — try refreshing.",
        "dashboard.five_hour.empty_tasks": "No tasks ran inside the current 5-hour window.",
        "dashboard.five_hour.by_task": "Today's tasks inside the window",
        "dashboard.five_hour.col.task": "Task",
        "dashboard.five_hour.col.project": "Project",
        "dashboard.five_hour.col.time": "Last activity",
        "dashboard.five_hour.col.tokens": "Tokens",
        "dashboard.five_hour.col.share": "% of 5h limit",
        "dashboard.five_hour.total.fmt": "Today inside window: %d tasks · %@ tokens · %@ of limit",

        // MARK: - Provider detail
        "provider_detail.count_total.fmt": "%d records · %@ total",
        "provider_detail.empty.title.fmt": "No data for %@",
        "provider_detail.empty.desc": "Configure an API Key and wait for the next scheduled fetch, or make sure the corresponding local log path exists.",
        "provider_detail.by_model": "By Model",
        "provider_detail.recent": "Recent Records",
        "provider_detail.api_key_guide.fmt": "How to get %@",
        "provider_detail.tokens.fmt": "%@ tokens",

        // MARK: - Model breakdown
        "models.title": "Model Breakdown",
        "models.empty": "No data",
        "models.col.model": "Model",
        "models.col.provider": "Provider",
        "models.col.tokens": "Tokens",
        "models.col.cost": "Cost",
        "models.chart.cost": "Cost",
        "models.chart.date": "Date",
        "models.chart.provider": "Provider",
        "models.chart.cost_usd": "Cost USD",

        // MARK: - Quota card
        "quotacard.empty": "No quota windows to display",
        "quotacard.updated.fmt": "Updated %@ · %@",
        "quotacard.reset.fmt": "Resets %@",
        "quotacard.usage.title": "Usage",
        "quotacard.usage.today": "Today",
        "quotacard.usage.week": "Last 7 days",
        "quotacard.usage.month": "Last 30 days",
        "quotacard.usage.tokens.fmt": "%@ tokens",

        // MARK: - Provider row / Cost card / Usage chart
        "providerrow.subtitle.fmt": "%d records · %@ tokens",
        "costcard.tokens.fmt": "%@ tokens",
        "usagechart.x.date": "Date",
        "usagechart.y.cost_usd": "Cost USD",
        "usagechart.legend.provider": "Provider",

        // MARK: - Breakeven
        "breakeven.header.fmt": "%@ · %@",
        "breakeven.tier.title": "Plan started",
        "breakeven.tier.subtitle": "Subscription began",
        "breakeven.first_breakeven": "First break-even",
        "breakeven.rate_300": "Break-even rate 300%",
        "breakeven.timeline.milestone.fmt": "Break-even rate hit %d%% · value %@",
        "breakeven.timeline.current.fmt": "Break-even rate %.0f%% (current)",
        "breakeven.timeline.value.fmt": "Value reached %@",
        "breakeven.hero.cheers": "Congrats!",
        "breakeven.hero.keep_going": "Keep going!",
        "breakeven.hero.title.done": "Broke even!",
        "breakeven.hero.title.almost": "Almost there",
        "breakeven.hero.subtitle.fmt": "You've earned back %@x your plan fee 🎉",
        "breakeven.metric.paid": "Paid",
        "breakeven.metric.paid.sub": "This month's plan fee",
        "breakeven.metric.value": "Value gained",
        "breakeven.metric.value.sub": "Equivalent token value",
        "breakeven.metric.saved": "Saved",
        "breakeven.metric.saved.sub": "Amount you saved",
        "breakeven.tier.fire": "Super Saver",
        "breakeven.tier.diamond": "Break-even Pro",
        "breakeven.tier.done": "Broke Even",
        "breakeven.tier.almost": "Almost There",
        "breakeven.tier.newbie": "Beginner",
        "breakeven.badge.usage_reached": "Your token usage has reached",
        "breakeven.badge.plan_value.fmt": "of the %@ plan value, equal to",
        "breakeven.badge.multiples.fmt": "%.2fx",
        "breakeven.badge.surpassed": "Surpassed",
        "breakeven.badge.users": "of users",
        "breakeven.invret.title": "Invested vs Returned",
        "breakeven.invret.desc": "More value for less money",
        "breakeven.invret.rate": "Break-even rate",
        "breakeven.invret.paid": "Paid",
        "breakeven.invret.gained": "Value gained",
        "breakeven.timeline.title": "Break-even Timeline",
        "breakeven.timeline.date_fmt": "MMM d",
        "breakeven.overview.title.fmt": "Usage Overview (%@)",
        "breakeven.overview.tokens": "Tokens used",
        "breakeven.overview.requests": "Requests",
        "breakeven.overview.month_eq": "Month equivalent",
        "breakeven.overview.view_models": "View model breakdown",
        "breakeven.api.title": "If billed via API",
        "breakeven.api.desc.fmt": "If you used %@ directly via API\nyou'd pay this month",
        "breakeven.api.saved": "Equivalent savings",
        "breakeven.api.saved_pct.fmt": "Saved %.1f%%",
        "breakeven.api.now_paid": "You only paid",
        "breakeven.api.plan_cost.fmt": "%@ plan fee",
        "breakeven.tip.label": "💡 Tip",
        "breakeven.tip.done.fmt": "Keep it up! You're fully leveraging the %@ plan ✨",
        "breakeven.tip.almost": "Use it a bit more — you're almost at break-even 💪",
        "breakeven.empty.title": "No subscriptions yet",
        "breakeven.empty.desc": "Add subscriptions like ChatGPT Plus / Claude Pro under Settings → Subscriptions.\nIf you're signed in to Claude Code / Codex CLI, head to Dashboard and wait a few seconds — subscriptions are auto-detected.",

        // MARK: - Probe results
        "probe.ok.fmt": "✓ Got sessionKey from %@/%@ (…%@), host=%@",
        "probe.err.fmt": "✗ %@",
        "quota.probe.success.fmt": "Got sessionKey from %@/%@ (…%@), host=%@",

        // MARK: - API Key labels & hints
        "apikey.hint.openai":      "Pulls cost data from api.openai.com /v1/organization/costs",
        "apikey.hint.anthropic":   "Pulls usage data from api.anthropic.com /v1/organizations/usage_report",

        // MARK: - ChromiumBrowser errors
        "browser.not_installed.fmt": "%@ not installed",
        "browser.no_cookies.fmt": "%@ has no Cookies file",
        "browser.sqlite_unavailable": "/usr/bin/sqlite3 is not available",
        "browser.sqlite_failed.fmt": "Reading SQLite failed: %@",
        "browser.no_session_key.fmt": "%@ has no claude.ai sessionKey (please sign in to claude.ai first)",
        "browser.keychain_missing.fmt": "%@ Safe Storage key is missing",
        "browser.keychain_denied.fmt": "%@ Safe Storage Keychain access denied (OSStatus=%@)",
        "browser.decrypt_failed.fmt": "Cookie decryption failed: %@",

        // MARK: - Downgrade detection
        "settings.tab.downgrade": "Downgrade Watch",
        "settings.downgrade.section.about": "About",
        "settings.downgrade.section.key": "Canary API Key",
        "settings.downgrade.section.control": "Probe Control",
        "settings.downgrade.intro": "Periodically probe Claude with a small fixed prompt set to detect whether your account has been silently downgraded or tagged (e.g. TOO_DUMB_TO_NEED_FABLE).",
        "settings.downgrade.disclaimer": "No packet capture is involved — only behavioral inference: request a specific model → check whether the returned model field and output_tokens deviate from the baseline.",
        "settings.downgrade.canary.label": "Canary API Key",
        "settings.downgrade.canary.hint": "User-level API key (sk-ant-api03-...), stored separately from your Admin key. Each probe consumes <30 tokens.",
        "settings.downgrade.enable": "Enable active canary probe",
        "settings.downgrade.interval": "Probe interval",
        "settings.downgrade.interval.hours.fmt": "Every %d h",
        "settings.downgrade.run_now": "Probe now",
        "settings.downgrade.reset_baseline": "Reset baseline",

        "dashboard.section.downgrade": "Claude routing health",
        "downgrade.card.title": "Claude routing health",
        "downgrade.card.details": "Open details",
        "downgrade.card.last.fmt": "Last probe %@",
        "downgrade.card.status.clean": "Clean",
        "downgrade.card.status.suspicious": "Suspicious",
        "downgrade.card.status.downgraded": "Downgraded",
        "downgrade.card.status.no_key": "Not configured",
        "downgrade.card.status.disabled": "Disabled",
        "downgrade.card.subtitle.clean": "No behavioral deviation from baseline observed in the last 24h.",
        "downgrade.card.subtitle.suspicious": "Short outputs or unusual stop_reason detected; not yet a confirmed downgrade.",
        "downgrade.card.subtitle.downgraded": "Requested tier > served tier confirmed (e.g. Opus requested, Sonnet returned).",
        "downgrade.card.subtitle.no_key": "Add a user-level API key in Settings → Downgrade Watch.",
        "downgrade.card.subtitle.disabled": "Active probing is off. Enable it in Settings.",

        "downgrade.detail.title": "Claude downgrade watch",
        "downgrade.detail.run_now": "Probe now",
        "downgrade.detail.disclaimer": "All signals are inferred from a few fixed probe calls against /v1/messages — no packet capture or reverse engineering.",
        "downgrade.detail.total.fmt": "%d events",
        "downgrade.detail.empty.title": "No events yet",
        "downgrade.detail.empty.desc": "Enable active probing and configure a Canary API key; events will populate automatically.",
        "downgrade.detail.row.raw": "Raw response",
        "downgrade.source.canary": "Active probe",
        "downgrade.source.passive": "Passive log",

        "sidebar.stego": "Stego detection",
        "dashboard.section.stego": "Claude Desktop stego",
        "stego.card.title": "Claude Desktop stego / browser injection",
        "stego.card.scan_now": "Scan now",
        "stego.card.details": "Details",
        "stego.card.last.fmt": "Last scan %@",
        "stego.card.status.unknown": "Not scanned",
        "stego.card.status.clean": "No anomaly",
        "stego.card.status.suspicious": "Suspicious",
        "stego.card.status.confirmed": "Stego codepoint hit",
        "stego.card.subtitle.never": "Tap Scan Now to check browser profiles and Claude Desktop caches for the reported stego characters.",
        "stego.card.subtitle.clean": "Browser profiles and Claude Desktop caches are clean.",
        "stego.card.subtitle.suspicious.fmt": "%d browser artifacts; %d unknown non-ASCII hits.",
        "stego.card.subtitle.confirmed.fmt": "%d reported Unicode codepoint hits; %d related browser artifacts.",
        "stego.detail.title": "Stego & browser injection detection",
        "stego.detail.header.generated.fmt": "Generated at %@",
        "stego.detail.header.never": "No report yet. Click Rescan below to start.",
        "stego.detail.rescan": "Rescan",
        "stego.detail.import.mitm": "Import mitmproxy / HAR",
        "stego.detail.export": "Export JSON report",
        "stego.detail.import.error": "Import failed",
        "stego.detail.browser.title": "Browser injection hits (P1+P2)",
        "stego.detail.browser.hint": "Walks NativeMessagingHosts / External Extensions / Extensions / Preferences under each Chromium-family profile and flags files containing Anthropic keywords.",
        "stego.detail.browser.empty": "No browser configuration files containing Anthropic keywords were found.",
        "stego.detail.browser.keywords.fmt": "Matched keywords: %@",
        "stego.detail.prompt.title": "System prompt Unicode hits (P3+P4)",
        "stego.detail.prompt.hint": "Anchored on \"Today's date\", detects the date separator (- → /) and three apostrophe channels (U+2019 / U+02BC / U+02B9).",
        "stego.detail.prompt.empty": "No suspicious Unicode characters found near Today's date.",
        "stego.detail.prompt.codepoint.fmt": "Codepoint: %@",
        "stego.detail.footer.sigver.fmt": "Signature version %@",
    ]
}
