import Foundation

enum LocalizationData_zhHant {
    static let table: [String: String] = [
        // MARK: - Language settings
        "lang.system": "跟隨系統",
        "lang.simplified_chinese": "簡體中文",
        "lang.traditional_chinese": "繁體中文",
        "lang.english": "English",
        "settings.language": "語言",
        "settings.language.section": "語言",
        "settings.language.picker": "介面語言",

        // MARK: - App / Root
        "app.title": "Tokenomics",
        "toolbar.refresh": "重新整理",
        "toolbar.refresh.help": "立即拉取所有 Collector",
        "sidebar.section.overview": "總覽",
        "sidebar.section.providers": "供應商",
        "sidebar.breakeven": "回本沒",
        "sidebar.dashboard": "儀表板",
        "sidebar.models": "模型分布",
        "sidebar.tasks": "任務詳情",
        "sidebar.logs": "拉取日誌",
        "logs.title": "拉取日誌",
        "logs.clear": "清空",
        "common.provider_not_exist": "供應商不存在",

        // MARK: - Tasks (Claude Code session-level usage)
        "tasks.title": "任務詳情",
        "tasks.reload": "重新掃描 ~/.claude/projects 與 ~/.codex/sessions",
        "tasks.filter.provider": "模型提供商",
        "tasks.filter.all_providers": "全部提供商",
        "tasks.filter.project": "專案",
        "tasks.filter.all_projects": "全部專案",
        "tasks.sort": "排序",
        "tasks.sort.cost": "按花費",
        "tasks.sort.tokens": "按 Token",
        "tasks.sort.recent": "按最近",
        "tasks.subtitle.fmt": "共 %d / %d 個任務",
        "tasks.empty.title": "未發現任務",
        "tasks.empty.desc": "請確認 Claude Code 或 Codex 已在本機使用過，並已產生 ~/.claude/projects 或 ~/.codex/sessions 下的會話日誌。",
        "tasks.detail.empty.title": "選擇左側任務查看詳情",
        "tasks.detail.empty.desc": "每個任務對應一個 Claude Code 或 Codex 會話（一個 .jsonl 檔案）。",
        "tasks.stat.cost": "總花費",
        "tasks.stat.tokens": "總 Token",
        "tasks.stat.messages": "請求次數",
        "tasks.stat.duration": "持續時長",
        "tasks.by_model": "按模型拆分",
        "tasks.col.model": "模型",
        "tasks.col.input": "輸入",
        "tasks.col.output": "輸出",
        "tasks.col.cache_w": "快取寫",
        "tasks.col.cache_r": "快取讀",
        "tasks.col.cost": "費用",
        "tasks.by_turn": "按使用者輪次拆分",
        "tasks.by_turn.hint": "每一行 = 一次你輸入的指令以及它引發的全部模型回覆（含 sidechain）",
        "tasks.by_turn.empty": "未辨識到使用者輸入輪次。",
        "tasks.turn.tokens.fmt": "Token %@",
        "tasks.turn.replies.fmt": "回覆 %d 次",
        "tasks.meta": "會話中繼資料",
        "tasks.meta.cwd": "工作目錄",
        "tasks.meta.branch": "Git 分支",
        "tasks.meta.file": "日誌檔案",
        "tasks.meta.first": "起始時間",
        "tasks.meta.last": "結束時間",

        // MARK: - Tasks: quota share & chart
        "tasks.quota_share.title": "佔訂閱額度比例",
        "tasks.quota_share.hint": "依目前 utilization，在同一 5 小時 / 每週視窗內所有任務間按 token 量分攤估算。",
        "tasks.quota_share.five_hour": "5 小時限額",
        "tasks.quota_share.weekly": "每週限額",
        "tasks.quota_share.of_limit": "限額",
        "tasks.quota_share.window_used.fmt": "視窗目前用量 %@",
        "tasks.quota_share.no_snapshot": "尚無額度快照，請至儀表板重新整理。",
        "tasks.project_timeline.title": "專案用量時間軸",
        "tasks.project_timeline.hint": "每個點代表該專案的一次任務，可由右側選單切換縱軸含義。",
        "tasks.project_timeline.x": "時間",
        "tasks.project_timeline.empty": "該專案尚無任務紀錄。",
        "tasks.project_timeline.count.fmt": "已繪製 %d 個任務",
        "tasks.project_timeline.metric.input": "輸入 Token",
        "tasks.project_timeline.metric.output": "輸出 Token",
        "tasks.project_timeline.metric.cache_read": "快取命中 Token",
        "tasks.project_timeline.metric.cache_creation": "快取建立 Token",
        "tasks.project_timeline.metric.cost": "費用",
        "tasks.project_timeline.range.day1": "過去 1 天",
        "tasks.project_timeline.range.day3": "過去 3 天",
        "tasks.project_timeline.range.day7": "過去 7 天",
        "tasks.project_timeline.range.day30": "過去 30 天",
        "tasks.project_timeline.range.all": "全部",

        // MARK: - Settings tabs
        "settings.tab.keys": "API Keys",
        "settings.tab.providers": "供應商",
        "settings.tab.subscriptions": "訂閱",
        "settings.tab.quotaSources": "額度採集",
        "settings.tab.display": "顯示",
        "settings.tab.pricing": "單價",
        "settings.tab.data": "資料",

        // MARK: - Settings: API Keys
        "settings.keys.intro": "在下方為各個服務商填寫 API Key，App 會用它們去拉取用量或餘額。",
        "settings.keys.col.provider": "服務商",
        "settings.keys.col.provider.sub": "AI 服務名稱",
        "settings.keys.col.usage": "用途",
        "settings.keys.col.usage.sub": "該 Key 用於呼叫哪個介面",
        "settings.keys.col.apikey": "API Key",
        "settings.keys.col.apikey.sub": "貼上你的金鑰並點擊「儲存」",
        "settings.keys.security": "金鑰儲存在系統 Keychain 中，不會隨資料庫匯出。",
        "settings.keys.section.note": "說明",
        "settings.keys.section.list": "金鑰列表",
        "settings.keys.empty": "所有內建供應商均已在「供應商」分頁下隱藏。",
        "settings.keys.placeholder.set": "已設定（輸入新值覆蓋）",
        "settings.keys.placeholder.unset": "未設定",
        "common.save": "儲存",
        "common.delete": "刪除",
        "common.cancel": "取消",
        "common.add": "新增",
        "common.edit": "編輯",
        "common.confirm": "確定",

        // MARK: - Settings: Display
        "settings.display.appearance": "外觀",
        "settings.display.mode": "顯示模式",
        "settings.display.currency": "貨幣",
        "settings.display.currency.label": "顯示",
        "settings.display.rate": "目前匯率",
        "settings.display.rate.refresh": "重新整理",

        // MARK: - Appearance modes
        "appearance.system": "跟隨系統",
        "appearance.light": "淺色模式",
        "appearance.dark": "深色模式",

        // MARK: - Currency
        "currency.usd": "美元 (USD)",
        "currency.cny": "人民幣 (CNY)",
        "currency.both": "雙顯示",

        // MARK: - Provider display names
        "provider.anthropic":   "Anthropic",
        "provider.openai":      "OpenAI",
        "provider.unknown":     "未知",

        // MARK: - Pricing
        "pricing.title": "模型單價（USD per 1M tokens）",
        "pricing.desc": "已內建 Anthropic / OpenAI 等常用模型公開單價；如需覆蓋，填寫下方表單或在列表中點擊「覆蓋」。",
        "pricing.search": "搜尋 provider 或 model",
        "pricing.col.model": "模型",
        "pricing.col.input": "輸入",
        "pricing.col.output": "輸出",
        "pricing.col.cacheWrite": "快取寫",
        "pricing.col.cacheRead": "快取讀",
        "pricing.custom_entries": "自訂條目",
        "pricing.overridden": "已覆蓋",
        "pricing.add_section": "手動新增 / 覆蓋單價",
        "pricing.placeholder.key": "key (provider:model)",
        "pricing.placeholder.input": "input",
        "pricing.placeholder.output": "output",
        "pricing.help.fill_form": "把目前價格填入下方表單以便覆蓋",
        "pricing.help.remove_override": "移除覆蓋，恢復內建單價",

        // MARK: - Data
        "data.section.db": "資料庫",
        "data.records.total": "記錄總數",
        "data.section.actions": "操作",
        "data.fetch_now": "立即拉取一次",
        "data.export_csv": "匯出 CSV",
        "data.section.path": "路徑",
        "data.path.desc": "資料儲存於 macOS SwiftData 容器（沙盒內 ~/Library/Containers/com.tokenomics.Tokenomics）",

        // MARK: - Providers settings
        "providers.intro": "控制 App 中顯示哪些供應商圖示。隱藏後將從側邊欄、儀表板彙總、API Keys 列表中移除。",
        "providers.tab.builtin": "內建",
        "providers.tab.custom": "自訂",
        "providers.toggle.show": "顯示",
        "providers.toggle.collect": "拉取",
        "providers.toggle.collect.help": "啟用後會按 5 分鐘間隔自動拉取",
        "providers.custom.title": "自訂供應商",
        "providers.custom.empty": "還沒有自訂供應商。點擊「新增」可以新增一個外部腳本端點。",
        "providers.custom.no_endpoint": "未設定端點",
        "common.new": "新增",
        "custom.editor.new": "新增自訂供應商",
        "custom.editor.edit": "編輯自訂供應商",
        "custom.editor.section.basic": "基礎",
        "custom.editor.section.http": "HTTP",
        "custom.editor.section.mapping": "欄位對映",
        "custom.editor.name": "名稱（顯示用）",
        "custom.editor.color": "顏色",
        "custom.editor.enable_collect": "啟用自動拉取",
        "custom.editor.endpoint": "Endpoint URL",
        "custom.editor.method": "方法",
        "custom.editor.headers": "Headers (JSON)",
        "custom.editor.body": "Body (JSON)",
        "custom.editor.records_path": "記錄陣列路徑 (recordsPath，留空代表根本身是陣列)",
        "custom.editor.model_field": "模型欄位",
        "custom.editor.input_field": "input tokens 欄位",
        "custom.editor.output_field": "output tokens 欄位",
        "custom.editor.timestamp_field": "時間戳欄位（選填）",
        "custom.editor.cost_field": "費用 USD 欄位（選填）",
        "custom.editor.requestid_field": "請求 ID 欄位（選填，用於去重）",
        "custom.editor.mapping.footer": "路徑語法：a.b[0].c  例：data.records 代表根物件 data 下的 records 陣列",
        "custom.editor.unnamed": "未命名",

        // MARK: - Subscriptions
        "subs.title": "訂閱套餐",
        "subs.desc": "新增你已訂閱的 ChatGPT Plus / Claude Pro 等，用來在「回本沒」頁面計算回本率。",
        "subs.empty.title": "還沒有訂閱記錄",
        "subs.empty.desc": "點擊右上角「新增」從預設套餐裡挑選，或自訂月費。",
        "subs.monthly.fmt": "$%.2f / 月",
        "subs.editor.new": "新增訂閱",
        "subs.editor.edit": "編輯訂閱",
        "subs.editor.preset_section": "快速選擇預設",
        "subs.editor.preset_picker": "預設套餐",
        "subs.editor.preset_custom": "（自訂）",
        "subs.editor.basic": "基本資訊",
        "subs.editor.provider": "供應商",
        "subs.editor.plan_name": "套餐名（如 Plus / Pro / Max 20x）",
        "subs.editor.monthly_usd": "月費 (USD)",

        // MARK: - Quota Sources
        "quota.title": "Claude 訂閱額度採集",
        "quota.desc": "Claude 的 5 小時 / 每週 額度可以從兩條資料源拉取。OAuth 介面雖然官方，但被限流（HTTP 429）的機率高；瀏覽器 Cookie 路徑走 claude.ai 網頁 API，限流策略獨立，是 OAuth 被限流時的兜底。",
        "quota.primary": "主路徑",
        "quota.primary.oauth": "OAuth 介面（預設）",
        "quota.primary.cookie": "瀏覽器 Cookie（繞開 OAuth 限流）",
        "quota.primary.cookie_desc": "優先從本機瀏覽器讀 claude.ai cookie，失敗時回退到 OAuth。",
        "quota.primary.oauth_desc": "優先 OAuth；遇到 429 / 401 時自動回退到瀏覽器 Cookie。",
        "quota.browser.priority": "瀏覽器優先順序",
        "quota.browser.priority.desc": "從上到下嘗試，先成功的瀏覽器優先使用其 cookie。點開關切換是否啟用某個瀏覽器。",
        "quota.test": "連通性測試",
        "quota.test.run": "立即從瀏覽器讀取 cookie",
        "quota.test.running": "正在測試…",
        "quota.test.keychain_hint": "第一次讀取會彈出系統鑰匙圈授權，點「永遠允許」即可。",

        // MARK: - Dashboard
        "dashboard.title": "AI Token 用量儀表板",
        "dashboard.rate.fmt": "匯率 1 USD = ¥%@",
        "dashboard.rate.last_update.fmt": " · 上次更新 %@",
        "dashboard.picker.currency": "貨幣",
        "dashboard.section.quota": "訂閱額度（Claude / Codex）",
        "dashboard.section.trend": "過去 14 天趨勢",
        "dashboard.section.by_provider": "按供應商彙總（本月）",
        "dashboard.section.recent": "最近 30 條明細",
        "dashboard.empty.title": "暫無資料",
        "dashboard.empty.desc": "請在「設定」中設定 API Key，或確保 Claude Code 已在本機產生過日誌。",
        "dashboard.cost.today": "今日",
        "dashboard.cost.week": "本週",
        "dashboard.cost.month": "本月",
        "dashboard.cost.total": "累計",
        "dashboard.recordrow.io.fmt": "in %@ · out %@",

        // MARK: - Dashboard: 5-hour limit breakdown (top section)
        "dashboard.five_hour.section": "5 小時限額",
        "dashboard.five_hour.pick_hint": "選擇一個供應商，查看目前 5 小時滾動視窗的使用情況，以及今日每個任務佔了多少百分比。",
        "dashboard.five_hour.window_used.fmt": "視窗目前使用率 %@",
        "dashboard.five_hour.window_resets.fmt": "%@ 重置",
        "dashboard.five_hour.no_snapshot": "尚未取得該供應商的額度快照，請嘗試重新整理。",
        "dashboard.five_hour.empty_tasks": "目前 5 小時視窗內沒有任務紀錄。",
        "dashboard.five_hour.by_task": "今日視窗內的任務",
        "dashboard.five_hour.col.task": "任務",
        "dashboard.five_hour.col.project": "專案",
        "dashboard.five_hour.col.time": "最近活動",
        "dashboard.five_hour.col.tokens": "Token",
        "dashboard.five_hour.col.share": "佔 5h 限額",
        "dashboard.five_hour.total.fmt": "今日視窗內：%d 個任務 · %@ tokens · 共佔 %@",

        // MARK: - Provider detail
        "provider_detail.count_total.fmt": "共 %d 條 · 累計 %@",
        "provider_detail.empty.title.fmt": "暫無 %@ 資料",
        "provider_detail.empty.desc": "設定 API Key 後等待下次定時拉取，或確認對應本機日誌路徑存在。",
        "provider_detail.by_model": "按模型",
        "provider_detail.recent": "最近明細",
        "provider_detail.api_key_guide.fmt": "如何取得 %@",
        "provider_detail.tokens.fmt": "%@ tokens",

        // MARK: - Model breakdown
        "models.title": "模型分布",
        "models.empty": "暫無資料",
        "models.col.model": "模型",
        "models.col.provider": "供應商",
        "models.col.tokens": "Token",
        "models.col.cost": "花費",
        "models.chart.cost": "花費",
        "models.chart.date": "日期",
        "models.chart.provider": "供應商",
        "models.chart.cost_usd": "花費 USD",

        // MARK: - Quota card
        "quotacard.empty": "無可顯示的額度視窗",
        "quotacard.updated.fmt": "更新於 %@ · %@",
        "quotacard.reset.fmt": "將於 %@ 重設",
        "quotacard.usage.title": "用量",
        "quotacard.usage.today": "今日",
        "quotacard.usage.week": "近 7 天",
        "quotacard.usage.month": "近 30 天",
        "quotacard.usage.tokens.fmt": "%@ tokens",

        // MARK: - Provider row / Cost card / Usage chart
        "providerrow.subtitle.fmt": "%d 筆 · %@ tokens",
        "costcard.tokens.fmt": "%@ tokens",
        "usagechart.x.date": "日期",
        "usagechart.y.cost_usd": "花費 USD",
        "usagechart.legend.provider": "供應商",

        // MARK: - Breakeven
        "breakeven.header.fmt": "%@ · %@",
        "breakeven.tier.title": "套餐生效",
        "breakeven.tier.subtitle": "開始使用",
        "breakeven.first_breakeven": "首次回本",
        "breakeven.rate_300": "回本率 300%",
        "breakeven.timeline.milestone.fmt": "回本率達到 %d%% · 價值 %@",
        "breakeven.timeline.current.fmt": "回本率 %.0f%% (目前)",
        "breakeven.timeline.value.fmt": "價值達到 %@",
        "breakeven.hero.cheers": "恭喜你！",
        "breakeven.hero.keep_going": "繼續加油！",
        "breakeven.hero.title.done": "已回本！",
        "breakeven.hero.title.almost": "還差一點",
        "breakeven.hero.subtitle.fmt": "你已經賺回套餐費用的 %@ 倍 🎉",
        "breakeven.metric.paid": "支付金額",
        "breakeven.metric.paid.sub": "本月套餐支出",
        "breakeven.metric.value": "獲得價值",
        "breakeven.metric.value.sub": "Token 等值價值",
        "breakeven.metric.saved": "節省金額",
        "breakeven.metric.saved.sub": "相當於省下",
        "breakeven.tier.fire": "血賺級用戶",
        "breakeven.tier.diamond": "回本達人",
        "breakeven.tier.done": "已回本",
        "breakeven.tier.almost": "接近回本",
        "breakeven.tier.newbie": "新手用戶",
        "breakeven.badge.usage_reached": "你的 Token 使用量已經達到",
        "breakeven.badge.plan_value.fmt": "%@ 套餐價值的",
        "breakeven.badge.multiples.fmt": "%.2f 倍",
        "breakeven.badge.surpassed": "超過了",
        "breakeven.badge.users": "的用戶",
        "breakeven.invret.title": "投入 vs 回報",
        "breakeven.invret.desc": "用更少的錢，獲得了更多的價值",
        "breakeven.invret.rate": "回本率",
        "breakeven.invret.paid": "支付",
        "breakeven.invret.gained": "獲得價值",
        "breakeven.timeline.title": "回本時間線",
        "breakeven.timeline.date_fmt": "M月d日",
        "breakeven.overview.title.fmt": "使用概覽 (%@)",
        "breakeven.overview.tokens": "Token 使用量",
        "breakeven.overview.requests": "請求次數",
        "breakeven.overview.month_eq": "本月等值",
        "breakeven.overview.view_models": "查看模型分布",
        "breakeven.api.title": "如果按 API 計費",
        "breakeven.api.desc.fmt": "如果你直接透過 %@ API 使用\n本月你需要支付",
        "breakeven.api.saved": "相當於省下",
        "breakeven.api.saved_pct.fmt": "省了 %.1f%%",
        "breakeven.api.now_paid": "而現在你只支付了",
        "breakeven.api.plan_cost.fmt": "%@ 套餐費用",
        "breakeven.tip.label": "💡 小提示",
        "breakeven.tip.done.fmt": "繼續保持！你正在充分利用 %@ 套餐的強大能力 ✨",
        "breakeven.tip.almost": "再多用一些，距離回本只差一點啦 💪",
        "breakeven.empty.title": "還沒新增任何訂閱",
        "breakeven.empty.desc": "請到「設定 → 訂閱」中新增你訂閱的 ChatGPT Plus / Claude Pro 等套餐。\n如果你登入了 Claude Code / Codex CLI，回到「儀表板」等幾秒，訂閱會被自動識別。",

        // MARK: - Probe results
        "probe.ok.fmt": "✓ 已從 %@/%@ 讀到 sessionKey（…%@），host=%@",
        "probe.err.fmt": "✗ %@",
        "quota.probe.success.fmt": "已從 %@/%@ 讀到 sessionKey（…%@），host=%@",

        // MARK: - API Key 標籤 & 說明
        "apikey.hint.openai":      "從 api.openai.com 拉取 /v1/organization/costs 費用資料",
        "apikey.hint.anthropic":   "從 api.anthropic.com 拉取 /v1/organizations/usage_report 使用資料",

        // MARK: - ChromiumBrowser errors
        "browser.not_installed.fmt": "%@ 未安裝",
        "browser.no_cookies.fmt": "%@ 未找到 Cookies 檔案",
        "browser.sqlite_unavailable": "系統未提供 /usr/bin/sqlite3",
        "browser.sqlite_failed.fmt": "讀取 SQLite 失敗：%@",
        "browser.no_session_key.fmt": "%@ 沒有 claude.ai 的 sessionKey（請先登入 claude.ai）",
        "browser.keychain_missing.fmt": "%@ Safe Storage 金鑰不存在",
        "browser.keychain_denied.fmt": "%@ Safe Storage 鑰匙圈存取被拒絕（OSStatus=%@）",
        "browser.decrypt_failed.fmt": "cookie 解密失敗：%@",
    ]
}
